# Generated by Django 4.2.7 on 2023-11-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_video_course_demo_video_coursevideos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
