# Generated by Django 4.2.7 on 2023-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
