# Generated by Django 4.2.7 on 2023-12-01 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='chef',
            field=models.ForeignKey(limit_choices_to={'is_chef': True}, on_delete=django.db.models.deletion.CASCADE, related_name='chef_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
