# Generated by Django 4.2.7 on 2023-12-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='course',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
